<H1 align=>Machine Learning algorithms</H1>

## Classification Algorithms

## 1. Naive Bayes
For Detailed Information: [Naive Bayes](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html)

In [63]:
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
Y = np.array([1, 1, 1, 2, 2, 2])
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X, Y)
clf.predict([[-0.8, -1]])

array([1])

### Accuracy Of The Prediction
For Detailed Information: [Accuracy Of The Prediction](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html)

## 2. SVM
For Detailed Information: [SVM](https://scikit-learn.org/stable/modules/svm.html#svm-kernels)

In [68]:
from sklearn import svm
X = [[0, 0], [1, 1]]
y = [0, 1]
clf = svm.SVC()
clf.fit(X, y)
clf.predict([[2., 2.]])

array([1])

In [69]:
from sklearn import svm
X = [[0, 0], [1, 1]]
y = [0, 1]
clf = svm.SVC(gamma=10000,C=10000)
clf.fit(X, y)
pred=clf.predict([[2,2],[4,5],[-1,-2]])
pred

array([1, 1, 1])

## 3. Decision Tree
For Detailed Information: [Decision Tree](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html)

In [70]:
from sklearn import tree
X = [[0, 0], [1, 1]]
Y = [0, 1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)
clf.predict([[2, 2]])

array([1])

## 4. Random Forest
For Detailed Information: [Random Forest](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html)

In [71]:
from sklearn.ensemble import RandomForestClassifier
X = [[0, 0], [1, 1]]
Y = [0, 1]
clf = RandomForestClassifier()
clf.fit(X, Y)
clf.predict([[2, 2]])

array([1])

## 5. AdaBoost
For Detailed Information:[AdaBoost](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html)

In [44]:
from sklearn.ensemble import AdaBoostClassifier
X = [[0, 0], [1, 1]]
Y = [0, 1]
clf = AdaBoostClassifier()
clf.fit(X, Y)
AdaBoostClassifier(n_estimators=100, random_state=0)
clf.predict([[2, 2]])

array([1])

## 6. Nearest Neighbors
For Detailed Information: [K Neighbors Classifier](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html)

In [62]:
from sklearn.neighbors import KNeighborsClassifier
X = [[0, 0], [1, 1]]
Y = [0, 1]
neigh = KNeighborsClassifier(n_neighbors =1)
neigh.fit(X, Y)
neigh.predict([[2,2]])

array([1])

##  Continuous Supervised Learning Algorithm

### 1. Linear Regression
For Detailed Information: [Linear Regression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html)


In [3]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2])) + 3
reg = LinearRegression().fit(X, y)
#r-sqaured score
reg.score(X, y)
#slope
reg.coef_
#intercept
reg.intercept_
#predict
reg.predict(np.array([[3, 5]]))

array([16.])

## Unsupervised Learning Algorithm

### 1. k-means clustering
For Detailed Information: [k-means clustering](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html) <br>
Visualization Blog: [www.naftaliharris.com](https://www.naftaliharris.com/blog/visualizing-k-means-clustering/)

**Note: Parameter: n_clusters parameter is generally changed as per the clustering requirement**

In [4]:
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0],[10, 2], [10, 4], [10, 0]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
#predict
print(kmeans.predict([[0, 0], [12, 3]]))
#centroid
print(kmeans.cluster_centers_)


[1 0]
[[10.  2.]
 [ 1.  2.]]


## Additional Content

### 1. Feature Scaling (MinMax)
For Detailed Information: [MinMax](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html)<br><br>
Notes: SVM and K-MEANS algorithms are affected by Feature Scaling whereas Decision trees and Linear Regression doesn't get affected.

In [9]:
from sklearn.preprocessing import MinMaxScaler
#works with numpy arrays only
import numpy as np
#each inner array stores specific feature value.
#Multiple features can also be stored inside the inner array.
weights=np.array([[115],[140],[175]])
scaler=MinMaxScaler()
rescaled_weight=scaler.fit_transform(weights)
rescaled_weight

array([[0.        ],
       [0.41666667],
       [1.        ]])

### 2. Bag of Words

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()
string1="Hi Katie the self driving car will be the last Best Seabastian"
string2="Hi Sebastian the machine learning class will be great great great Kate"
string3="Hi Katie the machine learning class will be most excellent"
email_list=[string1,string2,string3]
bag_of_words=vectorizer.fit(email_list)
bag_of_words=vectorizer.transform(email_list)
#Remember the indexing starts at zero.
#Checking any words first position
vectorizer.vocabulary_.get("great")

6

### 3. Stopwords

In [26]:
from nltk.corpus import stopwords
# If you use nltk.corpus for the first time if will throw some error
# Download the resources to continue. Procedure in next code block
sw=stopwords.words("english")


#### Downloading Procedure


In [25]:
import nltk
nltk.download()
#Use nltk.download('all', halt_on_error=False) to get all of the corpora except for the 'panlex_lite' corpus.

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

### 4. Stemming
For Detailed Information: [nltk.org](https://www.nltk.org/howto/stem.html)

In [30]:
from nltk.stem.snowball import SnowballStemmer
#There are differnt types of stemmer available
stemmer=SnowballStemmer("english")
#Example
print(stemmer.stem("responsiveness"))


respons


### 5. TfIdf Representation
For more information: [Medium Post](https://towardsdatascience.com/tf-idf-for-document-ranking-from-scratch-in-python-on-real-world-dataset-796d339a4089)