<H1 align=>Machine Learning algorithms</H1>

## Classification Algorithms

## 1. Naive Bayes
For Detailed Information: [Naive Bayes](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html)

In [63]:
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
Y = np.array([1, 1, 1, 2, 2, 2])
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X, Y)
clf.predict([[-0.8, -1]])

array([1])

### Accuracy Of The Prediction
For Detailed Information: [Accuracy Of The Prediction](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html)

from sklearn.metrics import accuracy_score
accuracy = clf.score(features_test, labels_test)
accuracy = accuracy_score(labels_test, pred)
    

## 2. SVM
For Detailed Information: [SVM](https://scikit-learn.org/stable/modules/svm.html#svm-kernels)

In [68]:
from sklearn import svm
X = [[0, 0], [1, 1]]
y = [0, 1]
clf = svm.SVC()
clf.fit(X, y)
clf.predict([[2., 2.]])

array([1])

In [69]:
from sklearn import svm
X = [[0, 0], [1, 1]]
y = [0, 1]
clf = svm.SVC(gamma=10000,C=10000)
clf.fit(X, y)
pred=clf.predict([[2,2],[4,5],[-1,-2]])
pred

array([1, 1, 1])

## 3. Decision Tree
For Detailed Information: [Decision Tree](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html)

In [70]:
from sklearn import tree
X = [[0, 0], [1, 1]]
Y = [0, 1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)
clf.predict([[2, 2]])

array([1])

## 4. Random Forest
For Detailed Information: [Random Forest](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html)

In [71]:
from sklearn.ensemble import RandomForestClassifier
X = [[0, 0], [1, 1]]
Y = [0, 1]
clf = RandomForestClassifier()
clf.fit(X, Y)
clf.predict([[2, 2]])

array([1])

## 5. AdaBoost
For Detailed Information:[AdaBoost](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html)

In [44]:
from sklearn.ensemble import AdaBoostClassifier
X = [[0, 0], [1, 1]]
Y = [0, 1]
clf = AdaBoostClassifier()
clf.fit(X, Y)
AdaBoostClassifier(n_estimators=100, random_state=0)
clf.predict([[2, 2]])

array([1])

## 6. Nearest Neighbors
For Detailed Information: [K Neighbors Classifier](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html)

In [62]:
from sklearn.neighbors import KNeighborsClassifier
X = [[0, 0], [1, 1]]
Y = [0, 1]
neigh = KNeighborsClassifier(n_neighbors =1)
neigh.fit(X, Y)
neigh.predict([[2,2]])

array([1])